# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSApp
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift'

  target 'iOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSAppUITests' do
    # Pods for testing
  end

end
